name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'libcord-tech/gauntlet'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Get current named version
        run: echo "VERSION=$(jq --raw-output '.version' build/manifest.json)" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Patch version name
        run: jq ".version_name = \"$VERSION-$DATE\"" build/manifest.json > build/manifest.json.tmp && mv build/manifest.json.tmp build/manifest.json && rm -f build/manifest.json.tmp

      - name: Zip build directory
        run: zip -r gauntlet-nightly.zip build/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gauntlet-nightly.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly-${{ env.DATE }}
          name: Gauntlet Nightly ${{ env.DATE }}
          body: |
            ⚠️ Gauntlet Nightly - Unstable Release ⚠️

            This is a nightly build generated from the latest code. It is provided for users who are fine with bugs and want to have the latest features. It may contain bugs and incomplete features. Use it at your own risk.

            For the latest stable release, please look at the [Releases](https://github.com/libcord-tech/gauntlet/releases/latest) page.
          draft: false
          prerelease: true
